server:
  port: 3002

#hunan-jinxiang:

shandong:
  host: http://222.173.24.186:9090//WebService/WebService.asmx/
  get-time-method-name: gksd_getsysdatetime
  purchase-method-name: gksd_webddi_purbill
  sale-method-name: gksd_webddi_salebill
  stockIn-method-name:  gksd_webddi_inv
#  access-token: E98867E37B14B6C1A3794BC95A2E1F57
#  account: lnss
#  password: D2124D
  account: ceshi
  password: 123456
  access-token: 710F2F0A5778728AAB04EB3ED1842758
  private-key: "MIICeAIBADANBgkqhkiG9w0BAQEFAASCAmIwggJeAgEAAoGBAL7cP6WlT4vbj5Pw
    8KmLdo1FJPvlXZrN2P8+HswzmodebQgWD3JWfBg14rSyXJhZ5bjKyi3ioNybii9A
    mts+j1ApuRa++GSZEhQDiPr9JJ6gCZumWNgOthTM7o4evozF7wB75UpiHh0DwRyj
    zzVwruFyN5ER8nftWv3D3X7V2U5dAgMBAAECgYEAj/beY3oQSHRzFqqVPa4e3Gyd
    ewwF0TEYT19yJ6F9HELTh1fsithFfpWWzaoEQj79EqiUXIwnvn/sebwHkvzbZ9Sm
    jXzPjL54IsWLz+4JHuZhBIN495Lc51KTZmglcA8Kr9dqdSUB5JSbreYXkNNj5fB2
    rPxR3x9oOJThDvXJoVkCQQDht5Sp0YyqmJk2jPJilvQmAWLeF7xkUYUGpNSyqGlU
    /u74/ZvvkoS32TSmTJqLUdtzPWIp+J1Ny1+9v+djGn8nAkEA2Hd8ngcXKZQp9CcP
    cLcMcs2dq2wluS40shZuHfZsanNE9zHQ0MfNv2XuN1Zinr5ydy4l+8D+4JufExr+
    JXI42wJAAesag1r5lBWZ78HA6Z+Y0Z3fZj3TZxLeS5EpEZ+mzYchJtKY+a9IG3vo
    G6W5Bogakl8qL2sigx/AX496+velrwJBANK7mBTcAD+ZHzKyKATqHvNQmtM8iIj7
    o49P6MnAkZEcQKKJ26i1KubO25cBwSabbyH5Sj8JhtewiK930r0vsosCQQDERu0a
    TyPunGzfCDsc4rUFQ5PR+Ys/zLmxHYJHD+67IlsLOXI1aiF/p/6kIlZHqVVwUe0J
    vTugILXMEY15LXUa"
  upload:
     ip: 180.169.118.244
     port: 21
     username: guoyaokonggushandong
     password: 8iLK96

anhuiguokong:
  host: http://www.gykgah.com:8067/WebDDIService.asmx
  token: gksd_getsysdatetime
  userid: gksd_webddi_purbill
  password: gksd_webddi_salebill
  private-key: "naMThpS71rmjMMYBFDOrLxdRDl/FGjeQl3gYt6UCPaXajoSKzs/LsM45RVz0h77JU9AV5dce0JCa7hu0IMtEp7adE7nbkQOOHeF8onEPqpkP/XjlDCsRyDFQHUkCkNEzxKpzUYaIpbLy1aper324kIDacp2ejPjXmdqpBKl1PTHnCow9MaJbdINH1jo/3oDoPSbsYvrtwu5mMPAVFpB8ka8DxqbQDqS/LlSSBLFjiyJSBHAOIJ7BBWmN1Xy/AaW4xs83QZJCtPeiL99pmAwVwPQ0qu2u+7KEQ+IQmCg0icOu33yB+J+FSflD77Ip0fQ1tnPv+K0mOJWaYK7uOpVsnQ==</Modulus><Exponent>AQAB</Exponent><P>0efLnfqCBsu7VG4Uw9ZElmwqDSI5TcpDcv1fnRYJQ3ymKWnwwHfZ5NBQLxiXoL1DRj+wi7KQLhtadZepfV03Tn2IwflTq3fb2fc0jjNfP1WGXxq3bdDVLriJ8fjar8a1rxcIyVZGrvt2FNw6k14A1kGpICXFSRp/EWSkpIRTEOc=</P><Q>wEDrN2JafCLon1wLyiuE7N1zma8vxDAnuz5rY4fcOHspICvqjzqAYIvj4yEblyNZUORfgf8J1UBvqqa6g+i7WWYks+KCzMMmIKt9PS8Hg2Z+ZkMmx4EQLbQjx9iOQJyZ+aOzlZgNxwlXJXW4Sf8yuvUv58MuNnhdytuN0Ehwcds=</Q><DP>e6v7fv+6nnBo1ezp1RyoWowuFoDkjF2wcc6xB+eU26tUZzAhBfVXbwYBSE5QAAei3H/n79bsNg4ttPz/gnpqfJdf/RF+Z5d99CU/VM0VwEYOnngqPMx+3kEiHWwGxOvp3dhPd/iaOryzrMS4ylznV1VmZSd73n97AG9wxfGk018=</DP><DQ>oZVunKwTdQY6EcZhOlh9bj9qK58sPG5k1mFODOdhVi9dj2aZzCvVPlAVBw8Ki2rwZKatByt97jgsInfjh36SCD9rVa1pVgQnBYpcxpHCdNQuJHEIJOH64Q7oi80dMnzshP7rry2PVtwo3JkmfTr6PlxZGSfYrXtZCWiito5Lw8U=</DQ><InverseQ>JvA3fAvkdAuLvxhG4hO5Cltaf0YilW2GcizC6geey8n9J1MOSvzt3bpr5r6NA3T7AhpqpcXiAqrHc0ZrkZGiKgVcGlK0WYT5iEqyblpIMw9e0xAdZlopfV2fFdN4rdu9zow/Zc0CWKtuhLaQfviGhU7KSq3LOhWxGD9UnAWCC8A=</InverseQ><D>h/on2atq7KptTqE+RQLc414lmVSbXSYZH8+E4sT/zdXHVbCXXBZ7CiSZ2m94r6+vUxDoEr8h4Z8bRdG366HrsxAfJujnsYtzh+r969HDRdGKrYcfbQOp7xo6lUhpYipTkY3Gs8htDyHxvsWbr52vG1dLGBtGrSvqLtkjetYCP6n1Tmkbi7quL6yZf2aaul2oQztiO1OqVqh6GIjHw98eQZ1vqq+gJfxIYS2Pjrb5S7rXnLyzIxDf2fWgPvokkEjChGqVvP/khJeW1H1JP9VAa71uMPbsZ8CEYWrQf9h1HQZwVjs2/qYIog5+rQhbF0slmr0w+H+YdNOLjdJRnJ26MQ=="



guoyaoyunnan:
  username: 6050
  password: 666666
  pseudoCode: dyc56789
  upload:
     ip: 180.169.118.244
     port: 21
     username: guoyaokongguyunnan
     password: fIhrwP

guoyaoguangzhou:
  username: SSGJ
  password: ssgj1234
  upload:
    ip: 180.169.118.244
    port: 21
    username: guoyaokongguguangzhou
    password: 0itlwG
